---
abstract: 'ESX and ESXi inventory'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::Exception: 0
  Test::MockModule: 0
  Test::MockObject: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: FusionInventory-Agent-Task-ESX
no_index:
  directory:
    - inc
    - t
requires:
  Getopt::Long: 0
  JSON: 0
  Pod::Usage: 0
  perl: 5.8.0
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: 2.2.1
