---
abstract: 'ESX and ESXi inventory'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Exception: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: FusionInventory-Agent-Task-ESX
no_index:
  directory:
    - inc
    - t
requires:
  FusionInventory::Agent: "\x02\x01\x08"
  Getopt::Long: 0
  HTTP::Cookies: 0
  LWP::UserAgent: 0
  XML::TreePP: 0
  perl: 5.8.0
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: 1.0.0
